apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: preprod

resources:
  - namespace.yaml
  - ../../base

nameSuffix: -preprod

images:
  - name: nginx
    newName: nginx
    newTag: "1.28.0"

replicas:
  - name: nginx
    count: 2

commonLabels:
  environment: preprod
